---
id: devmi-2013
base_name: can-developer-write-readable-code
tags:
- rabbit
- readablecode
- devmi
presentation_date: 2013/03/02
version: 2013.3.2.6
licenses:
- CC BY-SA 3.0
slideshare_id: devmi-2013
speaker_deck_id: kai-fa-zhe-hashi-shi-deridaburunakodowoshu-kerufalseka
ustream_id: 
vimeo_id: 
author:
  markup_language: :rd
  name: 須藤功平
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
